/**
 * emitter.mjs — Reconciliation-engine activation-metadata emitter (Epic #693 FA2, issue #695).
 *
 * Converts a single ALREADY-ELIGIBLE learning (one that passed
 * {@link module:reconcile/eligibility.classifyLearning} — i.e. carries a
 * non-empty `file_paths[]`) into the activation-metadata object a renderer
 * (the next wave) turns into `.claude/rules/<slug>.md` frontmatter.
 *
 * Pure function — no file I/O. Node 20+ stdlib only (`node:path` for dirname,
 * the sibling learnings/schema.mjs for the TTL-derived expiry).
 *
 * ── The never-always-on invariant (the "brandmauer") ─────────────────────────
 * docs/rule-authoring.md § "The Never-Always-On Invariant". Any rule with
 * `auto-generated: true` MUST carry ≥1 activation axis (`globs` OR `mode` OR
 * `host-class`), a `learning-key`, and an `expires-at`. This emitter ALWAYS
 * stamps `autoGenerated: true` / `alwaysApply: false`, always emits a
 * `learningKey` and an `expiresAt`, and THROWS when it cannot produce at least
 * one activation axis (empty globs AND no hostClass). It can never emit an
 * always-on auto-generated rule.
 *
 * `mode` is intentionally NOT emitted: a learning's `scope`
 * (local/private/public) is a privacy tier, NOT a session mode — conflating the
 * two would mis-gate the rule. The activation axes used here are `globs`
 * (always, derived from file_paths) and optionally `host-class`.
 *
 * The output key names match the camelCase RuleEntry fields the rule-loader
 * surfaces (`globs`, `description`, `learningKey`, `confidence`, `expiresAt`,
 * `autoGenerated`, `alwaysApply`, `hostClass`).
 */

import { dirname } from 'node:path';

import { deriveExpiresAt } from '../learnings/schema.mjs';

const DAY_MS = 86400 * 1000;
const DESCRIPTION_MAX = 120;

// The "born-dead expiry" floor (issue #741.1a). A rule whose NATURAL expiry
// (created_at + TTL) already sits in the past — or within this many days of
// `now` — at proposal time would be excluded on first read: rule-loader.mjs
// drops any rule whose `expires-at` satisfies `Date.parse(expiry) < Date.now()`
// (strict `<`). 7 days sits below every per-type TTL in LEARNING_TTL_DAYS
// (min 30d), so the floor only ever RAISES a near-dead/past expiry — it never
// shortens a healthy future one.
const MIN_RULE_DAYS_DEFAULT = 7;

// ── #1015: field-shape gates (VALIDATION, never transformation) ──────────────
// This emitter REJECTS agent-authored values whose SHAPE cannot be serialised
// into frontmatter safely. It deliberately does NOT escape or neutralise
// content: neutralisation of agent text happens exactly once, in the renderer's
// render path. Escaping here as well would double-escape the output — a defect
// invisible to a file-level diff, because each file still looks locally correct.
// Rejection is idempotent, so it composes safely with the renderer's sanitiser.

/**
 * Accepted shape for `learning.host_class`.
 *
 * `host-class` is by far the highest-escalation field this emitter copies: the
 * renderer serialises it UNQUOTED as `host-class: <value>`, so a newline in it
 * injects sibling TOP-LEVEL frontmatter keys. An injected `alwaysApply: true`
 * plus `expires-at: 2099-01-01` converts a scoped, expiring auto-generated rule
 * into a permanent always-on one — defeating BOTH the never-always-on
 * brandmauer below AND the expiry sweep, because each of those inspects the
 * emitter's in-memory values rather than the serialised document.
 *
 * `validateLearning` (scripts/lib/learnings/schema.mjs) only asserts "string or
 * null" for this field — ANY string, newlines included — and
 * `validateProposalRecord` performs no unknown-key rejection, so every key on a
 * proposal record is spread verbatim into the learning
 * (scripts/lib/memory-proposals/sink.mjs). That is the mechanism that makes an
 * attacker-shaped `host_class` reachable at all; this gate is where it stops.
 *
 * The pattern admits every value `classifyHost()` in scripts/lib/host-identity.mjs
 * can produce (`macos-arm64-m4pro`, `linux-x86_64`, `windows-arm64`,
 * `<osName>-<arch>`) with generous headroom, and rejects everything that could
 * alter frontmatter structure: control chars, whitespace, `:`, `#`, quotes, and
 * a leading `-` (a YAML sequence marker). The 64-char ceiling bounds the emitted
 * line; the longest real value today is 17 chars, so the ceiling is inert in
 * practice. Revisit if a future host taxonomy needs richer tokens.
 */
const HOST_CLASS_RE = /^[A-Za-z0-9][A-Za-z0-9._-]{0,63}$/;

// Characters that make a `file_paths[]` entry unsafe to serialise as a glob.
// The renderer emits each glob as `  - "<value>"`, so a control char (a newline
// above all) breaks out of the block sequence into new top-level frontmatter
// keys, and a quote character breaks out of the quoted scalar. Entries carrying
// either are SKIPPED — the same defense-in-depth posture as the
// glob-metacharacter guard below, and for the same reason: this emitter also
// processes learnings.jsonl records that predate the #900 argv/schema guards.
const UNSAFE_PATH_QUOTE_RE = /["']/;

// Control chars: C0 range (U+0000–U+001F, includes \n \r \t) plus DEL (U+007F).
// A newline in frontmatter would corrupt the YAML parse — stripping these is
// critical. Written with \u escapes so the source stays pure ASCII.
// eslint-disable-next-line no-control-regex
const CONTROL_CHARS_RE = /[\u0000-\u001F\u007F]/g;

// Non-global twin of CONTROL_CHARS_RE for stateless `.test()` calls. A /g regex
// carries `lastIndex` across calls, so testing with CONTROL_CHARS_RE directly
// would alternate true/false on identical input. Derived from the same `.source`
// so the two can never drift — and so this line stays pure ASCII (a literal
// control char here would be a NUL-class corruption; see
// .claude/rules/proven-pattern-nul-byte-corruption...).
const CONTROL_CHARS_TEST_RE = new RegExp(CONTROL_CHARS_RE.source);

/**
 * Slugify a string into a stable kebab-case token.
 * Lowercases, collapses every run of non-`[a-z0-9]` chars into a single `-`,
 * and trims leading/trailing `-`. UUID subjects produce ugly-but-stable keys.
 *
 * @param {string} s
 * @returns {string}
 */
function kebab(s) {
  return String(s)
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

// Glob metacharacters (issue #900-follow-up, Q3-MED). A top-level
// (dirname==='.') file_paths entry is emitted AS THE GLOB ITSELF below — so a
// stray '**' or '[ab]' entry (e.g. from an OLD learning record predating the
// #900 C / schema.mjs argv-boundary guards) must never reach the renderer
// verbatim, or it would produce an effectively always-on rule glob. Skipped
// here as defense-in-depth even though the argv (memory-propose.mjs) and
// schema (memory-proposals/schema.mjs) layers already reject these at write
// time — this emitter also processes learnings.jsonl entries that predate
// those guards.
const GLOB_METACHAR_RE = /[*?[\]{}]/;

/**
 * Derive non-empty directory globs from a learning's `file_paths`.
 *
 * For each path: take its directory (`path.dirname`) and emit `<dir>/**`. When
 * the file sits at the repo top level (`dirname` === '.'), emit the bare
 * basename pattern instead of `./**` (e.g. `"foo.mjs"`). Entries containing a
 * glob metacharacter (`* ? [ ] { }`) are skipped entirely — see
 * {@link GLOB_METACHAR_RE} — as are entries carrying a control char or a quote
 * character, which would break out of the renderer's `  - "<glob>"` sequence
 * item into new top-level frontmatter keys (#1015; see
 * {@link CONTROL_CHARS_TEST_RE} / {@link UNSAFE_PATH_QUOTE_RE}). Results are
 * deduped, order-preserving on first occurrence.
 *
 * @param {string[]} filePaths
 * @returns {string[]}
 */
function globsFromFilePaths(filePaths) {
  const out = [];
  const seen = new Set();
  for (const raw of filePaths) {
    if (typeof raw !== 'string' || raw === '') continue;
    if (GLOB_METACHAR_RE.test(raw)) continue;
    // #1015: frontmatter-structure guard. Skipping (never escaping) keeps this
    // idempotent and non-overlapping with the renderer's sanitiser.
    if (CONTROL_CHARS_TEST_RE.test(raw) || UNSAFE_PATH_QUOTE_RE.test(raw)) continue;
    const normalized = raw.replace(/\\/g, '/');
    const dir = dirname(normalized);
    const pattern = dir === '.' ? normalized : `${dir}/**`;
    if (!seen.has(pattern)) {
      seen.add(pattern);
      out.push(pattern);
    }
  }
  return out;
}

/**
 * Build a single-line, frontmatter-safe description from a learning.
 *
 * Source precedence: `insight` → `title` → `subject`. Takes the first sentence
 * (split on `. `), strips ALL newlines and control chars, collapses internal
 * whitespace, and hard-truncates to {@link DESCRIPTION_MAX} chars (appending
 * `…` when it had to cut).
 *
 * @param {object} learning
 * @returns {string}
 */
function buildDescription(learning) {
  const source =
    typeof learning.insight === 'string' && learning.insight !== ''
      ? learning.insight
      : learning.title || learning.subject || '';

  // First sentence — split on '. ' so the headline stays terse.
  const firstSentence = String(source).split('. ')[0];

  const cleaned = firstSentence
    .replace(CONTROL_CHARS_RE, ' ')
    .replace(/\s+/g, ' ')
    .trim()
    // A trailing period from the first sentence reads oddly once truncated.
    .replace(/\.$/, '');

  if (cleaned.length <= DESCRIPTION_MAX) return cleaned;
  // Reserve one char for the ellipsis.
  return `${cleaned.slice(0, DESCRIPTION_MAX - 1).trimEnd()}…`;
}

/**
 * Compute the `expiresAt` YYYY-MM-DD date string for the emitted rule.
 *
 * When `ruleExpiryDays` is a finite number, expiry = `created_at` + N days.
 * Otherwise delegate to {@link deriveExpiresAt} (per-type TTL, default 60d).
 * When `created_at` is missing/unparseable, fall back to the injectable `now`
 * (epoch ms or Date) so the result stays deterministic under test.
 *
 * The result is then FLOORED at `now + minRuleDays` (default
 * {@link MIN_RULE_DAYS_DEFAULT}) so an older learning whose natural expiry has
 * already elapsed — or sits within the floor window — never produces a
 * born-dead rule (issue #741.1a). The floor only ever raises the expiry; a
 * healthy future expiry passes through unchanged.
 *
 * @param {object} learning
 * @param {number|undefined} ruleExpiryDays
 * @param {number|Date|undefined} now
 * @param {number|undefined} minRuleDays - floor window in days; defaults to
 *   {@link MIN_RULE_DAYS_DEFAULT} when not a finite positive number.
 * @returns {string} YYYY-MM-DD
 */
function computeExpiresAt(learning, ruleExpiryDays, now, minRuleDays) {
  const toYmd = (iso) => String(iso).slice(0, 10);
  const nowMs = () =>
    now instanceof Date ? now.getTime() : typeof now === 'number' ? now : Date.now();

  let derivedMs;
  if (typeof ruleExpiryDays === 'number' && Number.isFinite(ruleExpiryDays)) {
    let baseMs = Date.parse(learning.created_at);
    if (!Number.isFinite(baseMs)) baseMs = nowMs();
    derivedMs = baseMs + ruleExpiryDays * DAY_MS;
  } else {
    // No explicit override → per-type TTL. deriveExpiresAt falls back to
    // `Date.now()` internally when created_at is missing; to keep the injectable
    // `now` honoured for tests, substitute its ISO form as created_at in that case.
    let createdAt = learning.created_at;
    if (typeof createdAt !== 'string' || !Number.isFinite(Date.parse(createdAt))) {
      createdAt = new Date(nowMs()).toISOString();
    }
    derivedMs = Date.parse(deriveExpiresAt(createdAt, learning.type));
  }

  const days =
    Number.isFinite(minRuleDays) && minRuleDays > 0 ? minRuleDays : MIN_RULE_DAYS_DEFAULT;
  const floorMs = nowMs() + days * DAY_MS;
  return toYmd(new Date(Math.max(derivedMs, floorMs)).toISOString());
}

/**
 * Convert one eligible learning into renderer-ready activation metadata.
 *
 * @param {object} learning - an eligible learning (non-empty `file_paths[]`),
 *   carrying `type`, `subject`/`title`, `insight`, `confidence`, `created_at`,
 *   and optionally `host_class`.
 * @param {object} [opts]
 * @param {number} [opts.ruleExpiryDays] - explicit expiry window in days; when a
 *   finite number, overrides the per-type TTL.
 * @param {number|Date} [opts.now] - injectable clock (defaults to `Date.now()`).
 *   Used for BOTH the born-dead expiry floor (`now + minRuleDays`, applied on
 *   every call — see {@link computeExpiresAt}) and, secondarily, as the base
 *   date when `created_at` is missing/unparseable. Because the floor consults
 *   it unconditionally, any test asserting a literal `expiresAt` MUST inject
 *   `now` — otherwise the wall clock eventually raises the floor past the
 *   derived expiry and the assertion silently starts measuring the floor.
 * @param {number} [opts.minRuleDays] - floor window (days) applied to the
 *   emitted expiry so it never falls in the past — see
 *   {@link computeExpiresAt} and {@link MIN_RULE_DAYS_DEFAULT}. Defaults
 *   internally when omitted; config plumbing for this is a later wave.
 * @returns {{
 *   globs: string[],
 *   description: string,
 *   learningKey: string,
 *   confidence: number,
 *   expiresAt: string,
 *   autoGenerated: true,
 *   alwaysApply: false,
 *   hostClass?: string,
 * }}
 * @throws {Error} when no activation axis can be produced (empty globs AND no
 *   hostClass) — the never-always-on invariant.
 */
export function toActivationMetadata(learning, { ruleExpiryDays, now, minRuleDays } = {}) {
  if (learning === null || typeof learning !== 'object' || Array.isArray(learning)) {
    throw new Error('emitter: learning must be a non-null object');
  }

  const filePaths = Array.isArray(learning.file_paths) ? learning.file_paths : [];
  const globs = globsFromFilePaths(filePaths);

  // #1015: `host_class` is copied straight into an UNQUOTED `host-class:`
  // frontmatter line by the renderer, so its SHAPE is load-bearing. Reject a
  // malformed value loudly rather than degrade to "no host axis" — a
  // structurally-invalid host_class is a corruption/injection signal, and
  // silently emitting the rest of the rule from the same record would hide it.
  // The engine wraps each learning in its own try/catch, so this throw degrades
  // to ONE recorded rejection with an auditable reason, never a crashed run.
  let hostClass;
  if (typeof learning.host_class === 'string' && learning.host_class !== '') {
    if (!HOST_CLASS_RE.test(learning.host_class)) {
      throw new Error(
        `emitter: host_class has an unsafe shape (${JSON.stringify(learning.host_class)}) — refusing to emit; ` +
          'the renderer serialises it as an unquoted `host-class:` line, so a newline / colon / quote there ' +
          'injects sibling top-level frontmatter keys (e.g. alwaysApply: true + a far-future expires-at), ' +
          `defeating the never-always-on brandmauer and the expiry sweep. Expected ${HOST_CLASS_RE.source}.`,
      );
    }
    hostClass = learning.host_class;
  }

  // The brandmauer: an auto-generated rule must carry ≥1 activation axis. If we
  // could derive neither a glob nor a host-class, refuse — never emit always-on.
  if (globs.length === 0 && hostClass === undefined) {
    throw new Error(
      'emitter: no activation axis (globs/host-class) — refusing to emit always-on auto-generated rule (never-always-on invariant)',
    );
  }

  const subjectOrTitle = learning.title || learning.subject || '';
  // `learningKey` becomes an unquoted `learning-key:` frontmatter line. The
  // subject half was already kebab'd; the TYPE half was not. Today that is safe
  // only because `eligibility.mjs`'s inverted CONVERT_TYPES allow-list admits a
  // fixed set of kebab-safe literals, for which `kebab()` is the identity — so
  // this call changes no currently-reachable key. It is cheap insurance against
  // the latent hazard the #1015 census flagged: widening that allow-list to a
  // pattern or a passthrough would otherwise turn this line into a live
  // frontmatter-injection point with nothing behind it.
  const learningKey = `${kebab(learning.type)}/${kebab(subjectOrTitle)}`;

  const confidence = typeof learning.confidence === 'number' ? learning.confidence : 0;

  const metadata = {
    globs,
    description: buildDescription(learning),
    learningKey,
    confidence,
    expiresAt: computeExpiresAt(learning, ruleExpiryDays, now, minRuleDays),
    autoGenerated: true,
    alwaysApply: false,
  };

  if (hostClass !== undefined) {
    metadata.hostClass = hostClass;
  }

  return metadata;
}
