/**
 * emitter.mjs — Reconciliation-engine activation-metadata emitter (Epic #693 FA2, issue #695).
 *
 * Converts a single ALREADY-ELIGIBLE learning (one that passed
 * {@link module:reconcile/eligibility.classifyLearning} — i.e. carries a
 * non-empty `file_paths[]`) into the activation-metadata object a renderer
 * (the next wave) turns into `.claude/rules/<slug>.md` frontmatter.
 *
 * Pure function — no file I/O. Node 20+ stdlib only (`node:path` for dirname,
 * the sibling learnings/schema.mjs for the TTL-derived expiry).
 *
 * ── The never-always-on invariant (the "brandmauer") ─────────────────────────
 * docs/rule-authoring.md § "The Never-Always-On Invariant". Any rule with
 * `auto-generated: true` MUST carry ≥1 activation axis (`globs` OR `mode` OR
 * `host-class`), a `learning-key`, and an `expires-at`. This emitter ALWAYS
 * stamps `autoGenerated: true` / `alwaysApply: false`, always emits a
 * `learningKey` and an `expiresAt`, and THROWS when it cannot produce at least
 * one activation axis (empty globs AND no hostClass). It can never emit an
 * always-on auto-generated rule.
 *
 * `mode` is intentionally NOT emitted: a learning's `scope`
 * (local/private/public) is a privacy tier, NOT a session mode — conflating the
 * two would mis-gate the rule. The activation axes used here are `globs`
 * (always, derived from file_paths) and optionally `host-class`.
 *
 * The output key names match the camelCase RuleEntry fields the rule-loader
 * surfaces (`globs`, `description`, `learningKey`, `confidence`, `expiresAt`,
 * `autoGenerated`, `alwaysApply`, `hostClass`).
 */

import { dirname } from 'node:path';

import { deriveExpiresAt } from '../learnings/schema.mjs';

const DAY_MS = 86400 * 1000;
const DESCRIPTION_MAX = 120;

// The "born-dead expiry" floor (issue #741.1a). A rule whose NATURAL expiry
// (created_at + TTL) already sits in the past — or within this many days of
// `now` — at proposal time would be excluded on first read: rule-loader.mjs
// drops any rule whose `expires-at` satisfies `Date.parse(expiry) < Date.now()`
// (strict `<`). 7 days sits below every per-type TTL in LEARNING_TTL_DAYS
// (min 30d), so the floor only ever RAISES a near-dead/past expiry — it never
// shortens a healthy future one.
const MIN_RULE_DAYS_DEFAULT = 7;

// Control chars: C0 range (U+0000–U+001F, includes \n \r \t) plus DEL (U+007F).
// A newline in frontmatter would corrupt the YAML parse — stripping these is
// critical. Written with \u escapes so the source stays pure ASCII.
// eslint-disable-next-line no-control-regex
const CONTROL_CHARS_RE = /[\u0000-\u001F\u007F]/g;

/**
 * Slugify a string into a stable kebab-case token.
 * Lowercases, collapses every run of non-`[a-z0-9]` chars into a single `-`,
 * and trims leading/trailing `-`. UUID subjects produce ugly-but-stable keys.
 *
 * @param {string} s
 * @returns {string}
 */
function kebab(s) {
  return String(s)
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

/**
 * Derive non-empty directory globs from a learning's `file_paths`.
 *
 * For each path: take its directory (`path.dirname`) and emit `<dir>/**`. When
 * the file sits at the repo top level (`dirname` === '.'), emit the bare
 * basename pattern instead of `./**` (e.g. `"foo.mjs"`). Results are deduped,
 * order-preserving on first occurrence.
 *
 * @param {string[]} filePaths
 * @returns {string[]}
 */
function globsFromFilePaths(filePaths) {
  const out = [];
  const seen = new Set();
  for (const raw of filePaths) {
    if (typeof raw !== 'string' || raw === '') continue;
    const normalized = raw.replace(/\\/g, '/');
    const dir = dirname(normalized);
    const pattern = dir === '.' ? normalized : `${dir}/**`;
    if (!seen.has(pattern)) {
      seen.add(pattern);
      out.push(pattern);
    }
  }
  return out;
}

/**
 * Build a single-line, frontmatter-safe description from a learning.
 *
 * Source precedence: `insight` → `title` → `subject`. Takes the first sentence
 * (split on `. `), strips ALL newlines and control chars, collapses internal
 * whitespace, and hard-truncates to {@link DESCRIPTION_MAX} chars (appending
 * `…` when it had to cut).
 *
 * @param {object} learning
 * @returns {string}
 */
function buildDescription(learning) {
  const source =
    typeof learning.insight === 'string' && learning.insight !== ''
      ? learning.insight
      : learning.title || learning.subject || '';

  // First sentence — split on '. ' so the headline stays terse.
  const firstSentence = String(source).split('. ')[0];

  const cleaned = firstSentence
    .replace(CONTROL_CHARS_RE, ' ')
    .replace(/\s+/g, ' ')
    .trim()
    // A trailing period from the first sentence reads oddly once truncated.
    .replace(/\.$/, '');

  if (cleaned.length <= DESCRIPTION_MAX) return cleaned;
  // Reserve one char for the ellipsis.
  return `${cleaned.slice(0, DESCRIPTION_MAX - 1).trimEnd()}…`;
}

/**
 * Compute the `expiresAt` YYYY-MM-DD date string for the emitted rule.
 *
 * When `ruleExpiryDays` is a finite number, expiry = `created_at` + N days.
 * Otherwise delegate to {@link deriveExpiresAt} (per-type TTL, default 60d).
 * When `created_at` is missing/unparseable, fall back to the injectable `now`
 * (epoch ms or Date) so the result stays deterministic under test.
 *
 * The result is then FLOORED at `now + minRuleDays` (default
 * {@link MIN_RULE_DAYS_DEFAULT}) so an older learning whose natural expiry has
 * already elapsed — or sits within the floor window — never produces a
 * born-dead rule (issue #741.1a). The floor only ever raises the expiry; a
 * healthy future expiry passes through unchanged.
 *
 * @param {object} learning
 * @param {number|undefined} ruleExpiryDays
 * @param {number|Date|undefined} now
 * @param {number|undefined} minRuleDays - floor window in days; defaults to
 *   {@link MIN_RULE_DAYS_DEFAULT} when not a finite positive number.
 * @returns {string} YYYY-MM-DD
 */
function computeExpiresAt(learning, ruleExpiryDays, now, minRuleDays) {
  const toYmd = (iso) => String(iso).slice(0, 10);
  const nowMs = () =>
    now instanceof Date ? now.getTime() : typeof now === 'number' ? now : Date.now();

  let derivedMs;
  if (typeof ruleExpiryDays === 'number' && Number.isFinite(ruleExpiryDays)) {
    let baseMs = Date.parse(learning.created_at);
    if (!Number.isFinite(baseMs)) baseMs = nowMs();
    derivedMs = baseMs + ruleExpiryDays * DAY_MS;
  } else {
    // No explicit override → per-type TTL. deriveExpiresAt falls back to
    // `Date.now()` internally when created_at is missing; to keep the injectable
    // `now` honoured for tests, substitute its ISO form as created_at in that case.
    let createdAt = learning.created_at;
    if (typeof createdAt !== 'string' || !Number.isFinite(Date.parse(createdAt))) {
      createdAt = new Date(nowMs()).toISOString();
    }
    derivedMs = Date.parse(deriveExpiresAt(createdAt, learning.type));
  }

  const days =
    Number.isFinite(minRuleDays) && minRuleDays > 0 ? minRuleDays : MIN_RULE_DAYS_DEFAULT;
  const floorMs = nowMs() + days * DAY_MS;
  return toYmd(new Date(Math.max(derivedMs, floorMs)).toISOString());
}

/**
 * Convert one eligible learning into renderer-ready activation metadata.
 *
 * @param {object} learning - an eligible learning (non-empty `file_paths[]`),
 *   carrying `type`, `subject`/`title`, `insight`, `confidence`, `created_at`,
 *   and optionally `host_class`.
 * @param {object} [opts]
 * @param {number} [opts.ruleExpiryDays] - explicit expiry window in days; when a
 *   finite number, overrides the per-type TTL.
 * @param {number|Date} [opts.now] - injectable clock used ONLY as a fallback when
 *   `created_at` is missing/unparseable (keeps expiry deterministic in tests).
 * @param {number} [opts.minRuleDays] - floor window (days) applied to the
 *   emitted expiry so it never falls in the past — see
 *   {@link computeExpiresAt} and {@link MIN_RULE_DAYS_DEFAULT}. Defaults
 *   internally when omitted; config plumbing for this is a later wave.
 * @returns {{
 *   globs: string[],
 *   description: string,
 *   learningKey: string,
 *   confidence: number,
 *   expiresAt: string,
 *   autoGenerated: true,
 *   alwaysApply: false,
 *   hostClass?: string,
 * }}
 * @throws {Error} when no activation axis can be produced (empty globs AND no
 *   hostClass) — the never-always-on invariant.
 */
export function toActivationMetadata(learning, { ruleExpiryDays, now, minRuleDays } = {}) {
  if (learning === null || typeof learning !== 'object' || Array.isArray(learning)) {
    throw new Error('emitter: learning must be a non-null object');
  }

  const filePaths = Array.isArray(learning.file_paths) ? learning.file_paths : [];
  const globs = globsFromFilePaths(filePaths);

  const hostClass =
    typeof learning.host_class === 'string' && learning.host_class !== ''
      ? learning.host_class
      : undefined;

  // The brandmauer: an auto-generated rule must carry ≥1 activation axis. If we
  // could derive neither a glob nor a host-class, refuse — never emit always-on.
  if (globs.length === 0 && hostClass === undefined) {
    throw new Error(
      'emitter: no activation axis (globs/host-class) — refusing to emit always-on auto-generated rule (never-always-on invariant)',
    );
  }

  const subjectOrTitle = learning.title || learning.subject || '';
  const learningKey = `${learning.type}/${kebab(subjectOrTitle)}`;

  const confidence = typeof learning.confidence === 'number' ? learning.confidence : 0;

  const metadata = {
    globs,
    description: buildDescription(learning),
    learningKey,
    confidence,
    expiresAt: computeExpiresAt(learning, ruleExpiryDays, now, minRuleDays),
    autoGenerated: true,
    alwaysApply: false,
  };

  if (hostClass !== undefined) {
    metadata.hostClass = hostClass;
  }

  return metadata;
}
