/**
 * renderer.mjs — Reconciliation-engine rule renderer (Epic #693 FA2, issue #695).
 *
 * Turns an eligible learning + its activation-metadata (from the sibling
 * {@link module:reconcile/emitter.toActivationMetadata}) into a complete,
 * loader-parseable `.claude/rules/<slug>.md` markdown document.
 *
 * Pure functions — NO file I/O. {@link renderRule} returns the markdown STRING
 * plus the intended path; it does NOT write `.claude/rules/`. Writing (after
 * operator approval) is FA3's job (issue #696).
 *
 * ── The never-always-on invariant (the "brandmauer") ─────────────────────────
 * docs/rule-authoring.md § "The Never-Always-On Invariant". Every emitted rule
 * carries `auto-generated: true` and MUST therefore carry ≥1 activation axis
 * (non-empty `globs` OR a `host-class`), a `learning-key`, and an `expires-at`.
 * The emitter already guards this, but {@link renderRule} defends it again —
 * it THROWS when handed metadata with empty globs AND no hostClass so the
 * renderer can never serialise an always-on auto-generated rule.
 *
 * Frontmatter is emitted in a fixed key order matching what the rule-loader
 * (`scripts/lib/rule-loader.mjs`) parses: `auto-generated`, `alwaysApply`,
 * `description`, block-style `globs:`, optional `host-class`, `learning-key`,
 * `confidence`, `expires-at`. Glob values are always double-quoted (the loader
 * strips surrounding quotes), which keeps `*`/`[`/`{` safe.
 *
 * @module reconcile/renderer
 */

import { createHash } from 'node:crypto';

/**
 * Slugify a string into a stable kebab-case token: lowercases, collapses every
 * run of non-`[a-z0-9]` chars into a single `-`, and trims leading/trailing `-`.
 *
 * @param {string} s
 * @returns {string}
 */
function kebab(s) {
  return String(s)
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

/**
 * Short, stable SHA-1 prefix (first 7 hex chars) of an input string.
 *
 * @param {string} input
 * @returns {string}
 */
function shortHash(input) {
  return createHash('sha1').update(String(input)).digest('hex').slice(0, 7);
}

/**
 * Derive a kebab-case, stable, idempotent slug for a learning's rule file.
 *
 * `slug = kebab(type) + '-' + kebab(title||subject) + '-' + sha1(`${type}/${title||subject}`)[:7]`.
 * The hash suffix gives collision safety while staying deterministic: the same
 * learning always yields the same slug; distinct learnings yield distinct slugs.
 *
 * Guard: when `type` is missing OR both `title` and `subject` are missing, fall
 * back to `'auto-' + sha1(JSON.stringify(learning))[:7]`. Never throws.
 *
 * @param {object} learning
 * @returns {string}
 */
export function deriveSlug(learning) {
  if (learning === null || typeof learning !== 'object' || Array.isArray(learning)) {
    return `auto-${shortHash(JSON.stringify(learning))}`;
  }

  const type = typeof learning.type === 'string' ? learning.type : '';
  const subjectOrTitle =
    (typeof learning.title === 'string' && learning.title !== '' ? learning.title : '') ||
    (typeof learning.subject === 'string' && learning.subject !== '' ? learning.subject : '');

  if (type === '' || subjectOrTitle === '') {
    return `auto-${shortHash(JSON.stringify(learning))}`;
  }

  const base = `${kebab(type)}-${kebab(subjectOrTitle)}`;
  const suffix = shortHash(`${type}/${subjectOrTitle}`);

  // A kebab of all-symbol inputs can be empty; the hash suffix keeps the slug
  // non-empty and stable regardless.
  return base === '' ? `auto-${suffix}` : `${base}-${suffix}`;
}

/**
 * Render the body's `## Evidence` section content from a learning's `evidence`.
 *
 * Array → one `- ` bullet per item; string → as-is; absent/empty →
 * `(no evidence recorded)`.
 *
 * @param {unknown} evidence
 * @returns {string}
 */
function renderEvidence(evidence) {
  if (Array.isArray(evidence)) {
    const lines = evidence
      .filter((e) => e !== null && e !== undefined && String(e) !== '')
      .map((e) => `- ${String(e)}`);
    return lines.length > 0 ? lines.join('\n') : '(no evidence recorded)';
  }
  if (typeof evidence === 'string' && evidence !== '') {
    return evidence;
  }
  return '(no evidence recorded)';
}

/**
 * Render a complete `.claude/rules/<slug>.md` document for an eligible learning.
 *
 * @param {object} learning - the eligible learning (carries `type`,
 *   `subject`/`title`, `insight`, `evidence`, `id`, `source_session`).
 * @param {object} metadata - activation metadata from the emitter:
 *   `{ globs: string[], description, learningKey, confidence, expiresAt,
 *      autoGenerated: true, alwaysApply: false, hostClass?: string }`.
 * @returns {{ slug: string, path: string, content: string }}
 * @throws {Error} when `metadata.globs` is empty AND `metadata.hostClass` is
 *   falsy — the never-always-on invariant (defends the emitter's guard).
 */
export function renderRule(learning, metadata) {
  if (metadata === null || typeof metadata !== 'object' || Array.isArray(metadata)) {
    throw new Error('renderer: metadata must be a non-null object');
  }

  const globs = Array.isArray(metadata.globs) ? metadata.globs : [];
  const hostClass =
    typeof metadata.hostClass === 'string' && metadata.hostClass !== ''
      ? metadata.hostClass
      : undefined;

  // The brandmauer: refuse to serialise an always-on auto-generated rule.
  if (globs.length === 0 && hostClass === undefined) {
    throw new Error(
      'renderer: no activation axis (globs/host-class) — refusing to render always-on auto-generated rule (never-always-on invariant)',
    );
  }

  const slug = deriveSlug(learning);
  const path = `.claude/rules/${slug}.md`;

  const humanTitle =
    (typeof learning.title === 'string' && learning.title !== '' ? learning.title : '') ||
    (typeof learning.subject === 'string' && learning.subject !== '' ? learning.subject : '') ||
    metadata.learningKey ||
    slug;

  const insight =
    typeof learning.insight === 'string' && learning.insight !== ''
      ? learning.insight
      : '(no insight recorded)';

  // ── Frontmatter (fixed key order; loader-parseable) ──────────────────────
  const fm = [];
  fm.push('---');
  fm.push('auto-generated: true');
  fm.push('alwaysApply: false');
  fm.push(`description: ${metadata.description}`);
  // OMIT the `globs:` key entirely when there are no globs (a host-class-only
  // activation axis). An empty `globs:` line parses in the loader as
  // `globs: []`, which short-circuits BEFORE the host-class gate runs
  // (`if (globs.length === 0) continue;`) — dropping the rule on every host. A
  // rule with no `globs:` key is treated as not glob-scoped, so it is gated
  // purely by `host-class:` (loads only on a matching host) — the intended
  // behavior, and still never always-on (host-class IS an activation axis).
  if (globs.length > 0) {
    fm.push('globs:');
    for (const glob of globs) {
      // Always double-quote — keeps `*`/`[`/`{` safe; loader strips quotes.
      fm.push(`  - "${glob}"`);
    }
  }
  if (hostClass !== undefined) {
    fm.push(`host-class: ${hostClass}`);
  }
  fm.push(`learning-key: ${metadata.learningKey}`);
  fm.push(`confidence: ${metadata.confidence}`);
  fm.push(`expires-at: ${metadata.expiresAt}`);
  fm.push('---');

  // ── Body (free markdown; does not affect frontmatter parsing) ────────────
  const learningId = learning.id ? String(learning.id) : 'n/a';
  const sourceSession = learning.source_session ? String(learning.source_session) : 'n/a';

  const body = [
    '',
    `# Auto-generated rule: ${humanTitle}`,
    '',
    insight,
    '',
    '## Evidence',
    renderEvidence(learning.evidence),
    '',
    '<!-- provenance (auto-generated by the reconciliation engine — do not hand-edit) -->',
    '## Provenance',
    `- learning-key: \`${metadata.learningKey}\``,
    `- learning-id: \`${learningId}\``,
    `- source-session: \`${sourceSession}\``,
    `- confidence: ${metadata.confidence}`,
    '- generated-by: reconciliation-engine (Epic #693 FA2 / #695)',
    `- expires-at: ${metadata.expiresAt}`,
    '',
  ];

  const content = `${fm.join('\n')}\n${body.join('\n')}`;

  return { slug, path, content };
}
