#!/usr/bin/env node
// check-rules.mjs — Validate .claude/rules/*.md files with auto-generated: true
// against the never-always-on invariant (FA4 #697 backstop for the reconcile emitter
// brandmauer in scripts/lib/reconcile/emitter.mjs ~line 193).
//
// Rules WITHOUT `auto-generated: true` in their frontmatter are SKIPPED — this
// gate only validates generated rules. Handwritten rules are not audited here.
//
// For every auto-generated rule, three invariants are checked:
//   (a) never-always-on: must have at least one activation axis — a non-empty
//       `globs` array OR a `host-class` key. A rule that is always-on
//       (globs null/empty AND no host-class) is a budget violation (#668 / #687).
//   (b) learning-key must be present (traceability back to the emitter source).
//   (c) expires-at must be present (auto-generated rules must have a TTL).
//
// Usage: check-rules.mjs <plugin-root>
// Outputs lines of the form "  PASS: ..." / "  FAIL: ..."
// Exit 0 = all invariants satisfied (or no auto-generated rules found); exit 1 = at least one failure.

import { existsSync, readdirSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { parseGlobsFrontmatter } from '../rule-loader.mjs';

const [, , pluginRoot] = process.argv;

if (!pluginRoot) {
  console.error('Usage: check-rules.mjs <plugin-root>');
  process.exit(1);
}

const RULES_DIR = join(pluginRoot, '.claude', 'rules');

let passed = 0;
let failed = 0;

function pass(msg) {
  console.log(`  PASS: ${msg}`);
  passed++;
}

function fail(msg) {
  console.log(`  FAIL: ${msg}`);
  failed++;
}

// ============================================================================
// Check: auto-generated rule invariants
// ============================================================================
console.log('--- Check: .claude/rules/ auto-generated rule invariants ---');

// If the rules directory doesn't exist, there's nothing to validate — all pass.
if (!existsSync(RULES_DIR)) {
  pass('no .claude/rules/ directory found — nothing to validate');
  console.log('');
  console.log(`Results: ${passed} passed, ${failed} failed`);
  process.exit(0);
}

let mdFiles;
try {
  mdFiles = readdirSync(RULES_DIR).filter((f) => f.endsWith('.md'));
} catch (err) {
  console.error(`  tool-error: cannot read rules directory: ${err.message}`);
  process.exit(2);
}

if (mdFiles.length === 0) {
  pass('no .md rule files found — nothing to validate');
  console.log('');
  console.log(`Results: ${passed} passed, ${failed} failed`);
  process.exit(0);
}

// Track whether we found any auto-generated rules at all.
let autoGeneratedCount = 0;

for (const name of mdFiles.sort()) {
  const filePath = join(RULES_DIR, name);
  let contents;
  try {
    contents = readFileSync(filePath, 'utf8');
  } catch (err) {
    console.error(`  tool-error: cannot read ${filePath}: ${err.message}`);
    continue;
  }

  let parsed;
  try {
    parsed = parseGlobsFrontmatter(contents);
  } catch {
    // Malformed frontmatter — not an auto-generated rule, skip.
    continue;
  }

  const { globs, meta } = parsed;

  // Only validate rules that explicitly declare auto-generated: true.
  if (meta['auto-generated'] !== true) continue;

  autoGeneratedCount++;
  const rel = `.claude/rules/${name}`;

  // (a) never-always-on: must have at least one activation axis.
  // globs is null (no frontmatter / no globs key) OR empty array → always-on.
  // host-class absent → no host-class axis.
  const hasGlobs = Array.isArray(globs) && globs.length > 0;
  const hasHostClass = Object.prototype.hasOwnProperty.call(meta, 'host-class');

  if (!hasGlobs && !hasHostClass) {
    fail(
      `${rel} — auto-generated rule is always-on (no activation axis: globs is absent/empty AND host-class absent). ` +
      'This violates the never-always-on invariant (#668/#687). Add a globs filter or host-class axis.',
    );
  }

  // (b) learning-key must be present.
  if (!Object.prototype.hasOwnProperty.call(meta, 'learning-key')) {
    fail(`${rel} — auto-generated rule is missing required frontmatter key: learning-key`);
  }

  // (c) expires-at must be present.
  if (!Object.prototype.hasOwnProperty.call(meta, 'expires-at')) {
    fail(`${rel} — auto-generated rule is missing required frontmatter key: expires-at`);
  }

  // Emit a PASS line only when the rule satisfies ALL three invariants:
  // an activation axis (globs or host-class) AND learning-key AND expires-at.
  // When any failed, the FAIL line(s) above already emitted.
  const lkOk = Object.prototype.hasOwnProperty.call(meta, 'learning-key');
  const eaOk = Object.prototype.hasOwnProperty.call(meta, 'expires-at');
  if ((hasGlobs || hasHostClass) && lkOk && eaOk) {
    pass(`${rel} — auto-generated rule satisfies all invariants`);
  }
}

if (autoGeneratedCount === 0) {
  pass('no auto-generated rules found — nothing to validate');
}

console.log('');
console.log(`Results: ${passed} passed, ${failed} failed`);

process.exit(failed > 0 ? 1 : 0);
