// CI-only commitlint configuration (#1477 item 4). The `commitlint` job in
// .gitlab-ci.yml passes it with `-g commitlint.ci.config.mjs`; the husky
// commit-msg hook keeps using commitlint.config.mjs unchanged.
//
// Why a second file: commitlint's built-in default ignores
// (@commitlint/is-ignored 19.8.1, lib/defaults.js) skip far more than the
// messages git and GitLab generate — any message with a `Merge …` line ANYWHERE
// (multiline regex, so one body line suffices), `revert <anything>`,
// `Reapply <anything>`, `amend!`/`fixup!`/`squash!`, version headers (`v1.2.3`,
// `chore(x): 1.2.3`), `Merged …`, `Automatic merge…`, `Auto-merged … into …`.
// Locally that leniency is wanted: `git revert`, `git commit --fixup` and
// `git pull` merges must not be blocked mid-work. In CI it is a hole, so this
// file turns the defaults off and accepts only the messages git and GitLab
// write themselves, matched on the FIRST LINE only.

import base from './commitlint.config.mjs';

// GitLab's merge-commit template and git's own fmt-merge-msg, e.g.
//   Merge branch 'fix/x' into 'main'                      (GitLab merges an MR)
//   Merge branch 'main' into fix/x                        (git merge main)
//   Merge remote-tracking branch 'origin/main' into fix/x (git merge origin/main)
//   Merge branch 'main' of host:group/project             (git pull)
// The git-local shapes occur inside MR ranges whenever a branch takes in main.
const MERGE_HEADER =
  /^Merge (branch|branches|remote-tracking branch|remote-tracking branches|tag|tags|commit) '[^']+'((, | and )'[^']+')*( of \S+)?( into \S+)?$/;

// git revert / GitLab's revert button, and git >= 2.44 reverting a revert:
//   Revert "fix: x"    Reapply "fix: x"
const REVERT_HEADER = /^(Revert|Reapply) ".+"$/;

/**
 * True when the commit's first line is a merge or revert message generated by
 * git or GitLab.
 * @param {string} message raw commit message as commitlint reads it
 * @returns {boolean}
 */
const isGeneratedHeader = (message) => {
  const header = message.split(/\r?\n/, 1)[0];
  return MERGE_HEADER.test(header) || REVERT_HEADER.test(header);
};

export default {
  ...base,
  defaultIgnores: false,
  ignores: [isGeneratedHeader],
};
