// CI-only commitlint configuration (#1477 item 4). The `commitlint` job in
// .gitlab-ci.yml passes it with `-g commitlint.ci.config.mjs`; the husky
// commit-msg hook keeps using commitlint.config.mjs unchanged.
//
// Why a second file: commitlint's built-in default ignores
// (@commitlint/is-ignored 19.8.1, lib/defaults.js) skip far more than the
// messages git and GitLab generate — any message with a `Merge …` line ANYWHERE
// (multiline regex, so one body line suffices), `revert <anything>`,
// `Reapply <anything>`, `amend!`/`fixup!`/`squash!`, version headers (`v1.2.3`,
// `chore(x): 1.2.3`), `Merged …`, `Automatic merge…`, `Auto-merged … into …`.
// Locally that leniency is wanted: `git revert`, `git commit --fixup` and
// `git pull` merges must not be blocked mid-work. In CI it is a hole, so this
// file turns the defaults off and accepts only the messages git and GitLab
// write themselves.
//
// The first line alone does not say who wrote a message (#1507 item 1): a
// normal commit whose subject merely LOOKS like a merge or a revert passed every
// rule. So a merge-shaped first line is accepted only from a commit git counts
// as a merge (two or more parents) — the CI job lints those in a separate
// `--git-log-args=--merges` pass that sets COMMITLINT_MERGE_COMMITS=1, every
// other call sets it to 0 — and a revert-shaped first line only together with
// the body line git and GitLab write under it.

import base from './commitlint.config.mjs';

// GitLab's merge-commit template and git's own fmt-merge-msg, e.g.
//   Merge branch 'fix/x' into 'main'                      (GitLab merges an MR)
//   Merge branch 'main' into fix/x                        (git merge main)
//   Merge remote-tracking branch 'origin/main' into fix/x (git merge origin/main)
//   Merge branch 'main' of host:group/project             (git pull)
// The git-local shapes occur inside MR ranges whenever a branch takes in main.
// The quoted part is `'.+?'`, not `'[^']+'`: git allows an apostrophe in a
// branch name (`git check-ref-format "refs/heads/fix/it's"` exits 0), and the
// default ignores this file replaces accepted such a merge. `'.+?'` also spans a
// list (`'a', 'b' and 'c'`), so there is no separate repetition group for one —
// with `.+?` inside a `(…)*` the match backtracks exponentially on a long
// non-matching header (measured 2026-10-02: 87 ms at 128 chars, doubling per
// extra `, 'a'`), a pipeline hang a commit message could trigger.
const MERGE_HEADER =
  /^Merge (branch|branches|remote-tracking branch|remote-tracking branches|tag|tags|commit) '.+?'( of \S+)?( into \S+)?$/;

// git revert / GitLab's revert button, and git >= 2.44 reverting a revert:
//   Revert "fix: x"    Reapply "fix: x"
const REVERT_HEADER = /^(Revert|Reapply) ".+"$/;

// The body line under a generated revert. git: `This reverts commit <sha>.`
// (also under `Reapply "…"`, and `This reverts commit <sha>, reversing` when a
// merge is reverted). GitLab's revert button: `This reverts commit <sha>` for a
// commit, `This reverts merge request !<iid>` for a merged MR (GitLab
// `Commit#revert_description`; this second form is taken from GitLab's source,
// not measured on this instance — the repo's history holds one revert, a git one).
const REVERTS_LINE = /^This reverts (commit [0-9a-f]{7,40}\b|merge request !\d+\b)/m;

/**
 * True when the message is a merge or revert message generated by git or
 * GitLab: a merge-shaped first line from a real merge commit (the caller says
 * so via COMMITLINT_MERGE_COMMITS=1), or a revert-shaped first line with git's
 * or GitLab's reverts line in the body.
 * @param {string} message raw commit message as commitlint reads it
 * @returns {boolean}
 */
const isGeneratedHeader = (message) => {
  const header = message.split(/\r?\n/, 1)[0];
  if (MERGE_HEADER.test(header)) return process.env.COMMITLINT_MERGE_COMMITS === '1';
  return REVERT_HEADER.test(header) && REVERTS_LINE.test(message);
};

export default {
  ...base,
  defaultIgnores: false,
  ignores: [isGeneratedHeader],
};
