/**
 * template.mjs — Canonical .vault.yaml template renderer for vault-backfill.
 *
 * Reads the template once from projects-baseline; subsequent calls use cache.
 * Part of scripts/vault-backfill.mjs (Issue #241).
 */

import { readFileSync, existsSync } from 'node:fs';
import { homedir } from 'node:os';
import { resolve } from 'node:path';

export const TEMPLATE_PATH = process.env.PROJECTS_BASELINE_DIR
  ? resolve(process.env.PROJECTS_BASELINE_DIR, 'templates/shared/.vault.yaml.template')
  : resolve(homedir(), 'Projects/projects-baseline/templates/shared/.vault.yaml.template');

const TODAY = new Date().toISOString().slice(0, 10);

let _templateContent = null;

/**
 * Load and cache the canonical template. Calls dieFn(2, ...) if missing.
 */
export function loadTemplate(dieFn) {
  if (_templateContent !== null) return _templateContent;

  if (!existsSync(TEMPLATE_PATH)) {
    dieFn(
      2,
      `canonical template not found at ${TEMPLATE_PATH} — ` +
        `set PROJECTS_BASELINE_DIR env var or check projects-baseline checkout at $HOME/Projects/projects-baseline`,
    );
  }

  try {
    _templateContent = readFileSync(TEMPLATE_PATH, 'utf8');
  } catch (err) {
    dieFn(2, `cannot read template at ${TEMPLATE_PATH}: ${err.message}`);
  }

  return _templateContent;
}

/**
 * Convert a kebab-case slug to a human-readable Title Case name.
 * e.g. "auth-service" → "Auth Service"
 */
export function slugToHumanName(slug) {
  return slug
    .split('-')
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(' ');
}

/**
 * Derive a kebab-case slug from a repo path (last segment).
 */
export function pathToSlug(repoPath) {
  const last = repoPath.split('/').filter(Boolean).pop() ?? repoPath;
  return last
    .toLowerCase()
    .replace(/[._]/g, '-')
    .replace(/[^a-z0-9-]/g, '')
    .replace(/-+/g, '-')
    .replace(/^-+|-+$/g, '');
}

/**
 * Render .vault.yaml content from the canonical template.
 *
 * Substitutions:
 *   {{PROJECT_NAME}} → humanName   (metadata.name, summary placeholder)
 *   metadata.slug    → slug         (overwrite the {{PROJECT_NAME}} echo on slug field)
 *   tier             → manifest tier
 *   owner            → fetched owner
 *   {{GITLAB_GROUP}}/{{PROJECT_NAME}} → full gitlab path_with_namespace
 *
 * @param {{ humanName: string, slug: string, tier: string, gitlabPath: string, owner: string }} opts
 * @param {string} templateContent - loaded template string
 * @returns {string}
 */
export function renderTemplate({ humanName, slug, tier, gitlabPath, owner }, templateContent) {
  let out =
    `# Generated by scripts/vault-backfill.mjs on ${TODAY} — review and update before committing.\n` +
    templateContent;

  // {{PROJECT_NAME}} → humanName (appears in metadata.name, summary)
  out = out.replace(/\{\{PROJECT_NAME\}\}/g, humanName);

  // metadata.slug line: after PROJECT_NAME substitution it reads slug: "humanName" — fix to actual slug
  out = out.replace(/^(\s*slug:\s*)"[^"]*"(.*)$/m, `$1"${slug}"$2`);

  // tier: active → tier: <manifest tier>
  out = out.replace(/^(\s*tier:\s*)active(.*)$/m, `$1${tier}$2`);

  // owner field
  out = out.replace(/^(\s*owner:\s*)\S+(.*)$/m, `$1${owner}$2`);

  // spec.links.gitlab — template uses {{GITLAB_GROUP}}/{{PROJECT_NAME}};
  // after PROJECT_NAME substitution: {{GITLAB_GROUP}}/humanName — replace both
  out = out.replace(/\{\{GITLAB_GROUP\}\}\/[^\n"]+/g, gitlabPath);

  return out;
}
