/**
 * tests/skills/claude-md-drift-check/vault-dir-parity-alias.test.mjs
 *
 * Check 7 (`vault-dir-parity`) and Check 9 probe 2a under the NEW reality that
 * this repo now ships a root `AGENTS.md`.
 *
 * THE BUG. Check 7 skipped for its whole life here ("requires both CLAUDE.md
 * and AGENTS.md (only one present)"). The moment a root AGENTS.md appears the
 * check starts running against two files — and both checks that read "both
 * instruction files" were written for two INDEPENDENT hand-maintained files.
 * Against a generated byte-identical copy (or a symlink) they must report
 * parity as satisfied, never a diff; and probe 2a must not report every
 * dangling rule citation TWICE. Either regression fires on every session close,
 * against a file the operator cannot even edit.
 *
 * The real error class must survive: two independent files that genuinely
 * disagree is still exactly what Check 7 exists for (#600).
 */

import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { spawnSync } from 'node:child_process';
import { mkdtempSync, mkdirSync, writeFileSync, rmSync, symlinkSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const CHECKER = resolve(__dirname, '../../../skills/claude-md-drift-check/checker.mjs');

/** @type {string} */
let root;

/** A CLAUDE.md body with a Session Config carrying `vault-integration.vault-dir`. */
function instructionFile(vaultDir, extra = '') {
  return [
    '# Fixture',
    '',
    '## Session Config',
    '',
    'persistence: true',
    'vault-integration:',
    '  enabled: true',
    `  vault-dir: ${vaultDir}`,
    '  mode: warn',
    '',
    extra,
    '',
  ].join('\n');
}

function runChecker() {
  const r = spawnSync('node', [CHECKER, '--mode', 'warn'], {
    encoding: 'utf8',
    cwd: root,
    env: { ...process.env, VAULT_DIR: root },
  });
  const line = (r.stdout || '').split('\n').find((l) => l.startsWith('{'));
  return { raw: r, json: line ? JSON.parse(line) : null };
}

beforeEach(() => {
  root = mkdtempSync(join(tmpdir(), 'drift-alias-'));
  // A .claude/rules/ dir with a single real rule keeps Check 9 active.
  mkdirSync(join(root, '.claude', 'rules'), { recursive: true });
  writeFileSync(join(root, '.claude', 'rules', 'development.md'), '# development\n', 'utf8');
});

afterEach(() => {
  rmSync(root, { recursive: true, force: true });
});

describe('Check 7 — AGENTS.md is an alias of CLAUDE.md', () => {
  it('RUNS and reports no error for a byte-identical generated copy', () => {
    const body = instructionFile('~/Projects/vault');
    writeFileSync(join(root, 'CLAUDE.md'), body, 'utf8');
    writeFileSync(join(root, 'AGENTS.md'), body, 'utf8');

    const { json } = runChecker();
    expect(json.checks_run).toContain('vault-dir-parity');
    expect(json.errors.filter((e) => e.check === 'vault-dir-parity')).toEqual([]);
    expect(json.checks_skipped.join('|')).not.toMatch(/vault-dir-parity/);
  });

  it('RUNS and reports no error for a symlinked AGENTS.md', () => {
    writeFileSync(join(root, 'CLAUDE.md'), instructionFile('~/Projects/vault'), 'utf8');
    symlinkSync('CLAUDE.md', join(root, 'AGENTS.md'));

    const { json } = runChecker();
    expect(json.checks_run).toContain('vault-dir-parity');
    expect(json.errors.filter((e) => e.check === 'vault-dir-parity')).toEqual([]);
  });
});

describe('Check 7 — two independent files (the class it exists for)', () => {
  it('still errors when the two files declare different vault-dirs', () => {
    writeFileSync(join(root, 'CLAUDE.md'), instructionFile('~/Projects/vault'), 'utf8');
    writeFileSync(join(root, 'AGENTS.md'), instructionFile('~/dead/path'), 'utf8');

    const { json } = runChecker();
    expect(json.checks_run).toContain('vault-dir-parity');
    const errs = json.errors.filter((e) => e.check === 'vault-dir-parity');
    expect(errs).toHaveLength(1);
    expect(errs[0].file).toBe('AGENTS.md');
    expect(errs[0].message).toMatch(/~\/Projects\/vault/);
    expect(errs[0].message).toMatch(/~\/dead\/path/);
  });

  it('still skips when only one instruction file is present', () => {
    writeFileSync(join(root, 'CLAUDE.md'), instructionFile('~/Projects/vault'), 'utf8');
    const { json } = runChecker();
    expect(json.checks_run).not.toContain('vault-dir-parity');
    expect(json.checks_skipped.join('|')).toMatch(/vault-dir-parity: requires both/);
  });
});

describe('Check 9 probe 2a — no double-reporting through the alias', () => {
  const dangling = 'See .claude/rules/does-not-exist.md for the rule.';

  it('reports a dangling rule citation ONCE when AGENTS.md is an alias', () => {
    // BUG: probe 2a iterates ['CLAUDE.md', 'AGENTS.md']. With a byte-identical
    // AGENTS.md every defect in CLAUDE.md is counted twice — one defect, two
    // errors, and in `--mode strict` a doubled blocking surface.
    const body = instructionFile('~/Projects/vault', dangling);
    writeFileSync(join(root, 'CLAUDE.md'), body, 'utf8');
    writeFileSync(join(root, 'AGENTS.md'), body, 'utf8');

    const { json } = runChecker();
    const errs = json.errors.filter((e) => e.check === 'rule-scoping' && e.extracted === 'does-not-exist.md');
    expect(errs).toHaveLength(1);
    expect(errs[0].file).toBe('CLAUDE.md');
  });

  it('reports the citation in BOTH files when they are genuinely independent', () => {
    writeFileSync(join(root, 'CLAUDE.md'), instructionFile('~/Projects/vault', dangling), 'utf8');
    writeFileSync(join(root, 'AGENTS.md'), instructionFile('~/other', dangling), 'utf8');

    const { json } = runChecker();
    const files = json.errors
      .filter((e) => e.check === 'rule-scoping' && e.extracted === 'does-not-exist.md')
      .map((e) => e.file)
      .sort();
    expect(files).toEqual(['AGENTS.md', 'CLAUDE.md']);
  });
});
