/**
 * emitter.test.mjs — Unit tests for the #695 Reconciliation-engine
 * activation-metadata emitter (`toActivationMetadata`).
 *
 * Covers:
 *   - Happy path: globs/description/learningKey/confidence + auto-generated flags.
 *   - Explicit ruleExpiryDays vs per-type default expiry (literal YYYY-MM-DD).
 *   - The never-always-on invariant throw (empty file_paths AND no host_class).
 *   - host-class as the sole activation axis.
 *   - Newline sanitization in description.
 *   - title preferred over subject for learningKey.
 *   - confidence passthrough + default-to-0.
 */

import { describe, it, expect } from 'vitest';

import { toActivationMetadata } from '../../../scripts/lib/reconcile/emitter.mjs';

/** A fully-eligible fragile-pattern learning fixture. */
function fragileLearning(overrides = {}) {
  return {
    type: 'fragile-pattern',
    subject: 'zx-imports',
    insight: 'session.ts churns. More text.',
    confidence: 0.8,
    file_paths: ['scripts/lib/autopilot/worktree-pipeline.mjs'],
    created_at: '2026-06-21T00:00:00Z',
    ...overrides,
  };
}

describe('toActivationMetadata — happy path', () => {
  it('derives a single dir-glob from the file path', () => {
    const meta = toActivationMetadata(fragileLearning(), {});
    expect(meta.globs).toEqual(['scripts/lib/autopilot/**']);
  });

  it('stamps autoGenerated true and alwaysApply false', () => {
    const meta = toActivationMetadata(fragileLearning(), {});
    expect(meta.autoGenerated).toBe(true);
    expect(meta.alwaysApply).toBe(false);
  });

  it('builds learningKey from type/kebab(subject)', () => {
    const meta = toActivationMetadata(fragileLearning(), {});
    expect(meta.learningKey).toBe('fragile-pattern/zx-imports');
  });

  it('passes confidence through unchanged', () => {
    const meta = toActivationMetadata(fragileLearning(), {});
    expect(meta.confidence).toBe(0.8);
  });

  it('builds description as the first sentence with no trailing period', () => {
    const meta = toActivationMetadata(fragileLearning(), {});
    expect(meta.description).toBe('session.ts churns');
  });
});

describe('toActivationMetadata — expiry', () => {
  it('honours an explicit ruleExpiryDays (created_at + 45 days)', () => {
    const meta = toActivationMetadata(fragileLearning(), { ruleExpiryDays: 45 });
    expect(meta.expiresAt).toBe('2026-08-05');
  });

  it('derives the per-type default expiry (fragile-pattern → 60d) when no override', () => {
    const meta = toActivationMetadata(fragileLearning(), {});
    expect(meta.expiresAt).toBe('2026-08-20');
  });
});

describe('toActivationMetadata — never-always-on invariant', () => {
  it('throws when there is no activation axis (empty file_paths AND no host_class)', () => {
    const learning = fragileLearning({ file_paths: [] });
    expect(() => toActivationMetadata(learning, {})).toThrow(
      /never-always-on|activation axis/,
    );
  });

  it('does NOT throw when host_class is the sole axis (empty file_paths)', () => {
    const learning = fragileLearning({
      file_paths: [],
      host_class: 'macos-arm64-m4pro',
    });
    const meta = toActivationMetadata(learning, {});
    expect(meta.hostClass).toBe('macos-arm64-m4pro');
  });
});

describe('toActivationMetadata — description sanitization', () => {
  it('strips newlines from the description', () => {
    const learning = fragileLearning({
      insight: 'first line\nsecond line embedded in the same sentence',
    });
    const meta = toActivationMetadata(learning, {});
    expect(meta.description.includes('\n')).toBe(false);
  });
});

describe('toActivationMetadata — learningKey source precedence', () => {
  it('prefers title over subject for the learningKey', () => {
    const learning = fragileLearning({
      title: 'Worktree Pipeline Hang',
      subject: 'zx-imports',
    });
    const meta = toActivationMetadata(learning, {});
    expect(meta.learningKey).toBe('fragile-pattern/worktree-pipeline-hang');
  });
});

describe('toActivationMetadata — confidence default', () => {
  it('defaults confidence to 0 when absent', () => {
    const learning = fragileLearning({ confidence: undefined });
    const meta = toActivationMetadata(learning, {});
    expect(meta.confidence).toBe(0);
  });
});
