/**
 * emitter.test.mjs — Unit tests for the #695 Reconciliation-engine
 * activation-metadata emitter (`toActivationMetadata`).
 *
 * Covers:
 *   - Happy path: globs/description/learningKey/confidence + auto-generated flags.
 *   - Explicit ruleExpiryDays vs per-type default expiry (literal YYYY-MM-DD).
 *   - The never-always-on invariant throw (empty file_paths AND no host_class).
 *   - host-class as the sole activation axis.
 *   - Newline sanitization in description.
 *   - title preferred over subject for learningKey.
 *   - confidence passthrough + default-to-0.
 */

import { createRequire } from 'node:module';

import { describe, it, expect } from 'vitest';

import { toActivationMetadata } from '../../../scripts/lib/reconcile/emitter.mjs';
// Imported READ-ONLY, to prove the emitter's key survives the renderer's
// machine-value assert (or, for a hostile type, is rejected by it).
import { renderRule } from '../../../scripts/lib/reconcile/renderer.mjs';

// picomatch is a transitive dependency (resolved the same way rule-loader.mjs
// resolves it) — used ONLY to prove the #1089 falsification claim: any glob
// this emitter DOES produce must be matchable by the SAME matcher the loader
// uses at runtime, not merely "look scoped".
const picomatch = createRequire(import.meta.url)('picomatch');

/**
 * File-wide frozen clock for every expiry assertion.
 *
 * `computeExpiresAt` FLOORS the emitted expiry at `now + minRuleDays` (default
 * 7d, the born-dead floor of #741.1a). Without an injected `now`, that floor
 * tracks the wall clock, so any literal expiry assertion becomes a date time
 * bomb: it silently flips from "measures the derived expiry" to "measures the
 * floor" once the wall clock walks past `derived - 7d`. That is exactly what
 * happened to the two 45d assertions below on 2026-07-30 (floor 2026-08-06
 * overtook the derived 2026-08-05).
 *
 * 2026-07-05 puts the floor at 2026-07-12, which sits 24 days below the
 * earliest asserted expiry (2026-08-05) and 39 below the latest (2026-08-20).
 * Every assertion therefore keeps measuring the DERIVED expiry, never the
 * floor — and, being clock-independent, keeps doing so forever.
 */
const FROZEN_NOW = new Date('2026-07-05T00:00:00Z');

/** A fully-eligible fragile-pattern learning fixture. */
function fragileLearning(overrides = {}) {
  return {
    type: 'fragile-pattern',
    subject: 'zx-imports',
    insight: 'session.ts churns. More text.',
    confidence: 0.8,
    file_paths: ['scripts/lib/autopilot/worktree-pipeline.mjs'],
    created_at: '2026-06-21T00:00:00Z',
    ...overrides,
  };
}

describe('toActivationMetadata — happy path', () => {
  it('derives a single dir-glob from the file path', () => {
    const meta = toActivationMetadata(fragileLearning(), {});
    expect(meta.globs).toEqual(['scripts/lib/autopilot/**']);
  });

  it('stamps autoGenerated true and alwaysApply false', () => {
    const meta = toActivationMetadata(fragileLearning(), {});
    expect(meta.autoGenerated).toBe(true);
    expect(meta.alwaysApply).toBe(false);
  });

  it('builds learningKey from type/kebab(subject)', () => {
    const meta = toActivationMetadata(fragileLearning(), {});
    expect(meta.learningKey).toBe('fragile-pattern/zx-imports');
  });

  it('passes confidence through unchanged', () => {
    const meta = toActivationMetadata(fragileLearning(), {});
    expect(meta.confidence).toBe(0.8);
  });

  it('builds description as the first sentence with no trailing period', () => {
    const meta = toActivationMetadata(fragileLearning(), {});
    expect(meta.description).toBe('session.ts churns');
  });
});

// Every test in this group asserts a DERIVED expiry, so each one injects
// FROZEN_NOW to hold the born-dead floor (now + 7d = 2026-07-12) well below
// the asserted value. Dropping the injection does not merely make the test
// clock-dependent — it silently degrades the assertion into a floor
// measurement, which is how the two 45d cases went red on 2026-07-30.
describe('toActivationMetadata — expiry', () => {
  it('honours an explicit ruleExpiryDays (created_at + 45 days)', () => {
    // 2026-06-21 + 45d = 2026-08-05, 24 days above the floor.
    const meta = toActivationMetadata(fragileLearning(), {
      ruleExpiryDays: 45,
      now: FROZEN_NOW,
    });
    expect(meta.expiresAt).toBe('2026-08-05');
  });

  it('derives the per-type explicit expiry (fragile-pattern → 45d) when no override', () => {
    // Same 2026-08-05, but via LEARNING_TTL_DAYS['fragile-pattern'] = 45.
    const meta = toActivationMetadata(fragileLearning(), { now: FROZEN_NOW });
    expect(meta.expiresAt).toBe('2026-08-05');
  });

  it('falls through to the registry default (60d) for a type absent from LEARNING_TTL_DAYS', () => {
    // 2026-06-21 + 60d = 2026-08-20, 39 days above the floor.
    const meta = toActivationMetadata(
      {
        type: 'totally-unknown-type',
        subject: 'zx-imports',
        insight: 'session.ts churns. More text.',
        confidence: 0.8,
        file_paths: ['scripts/lib/autopilot/worktree-pipeline.mjs'],
        created_at: '2026-06-21T00:00:00Z',
      },
      { now: FROZEN_NOW },
    );
    expect(meta.expiresAt).toBe('2026-08-20');
  });
});

describe('toActivationMetadata — born-dead expiry floor (#741.1a)', () => {
  it('floors a PAST natural expiry to now + 7 days (default floor)', () => {
    // created_at 2026-01-01 + fragile-pattern TTL (45d) → natural expiry
    // 2026-02-15, already in the past relative to `now` below. Fake-regression
    // check: without the Math.max floor this would assert '2026-02-15', not
    // '2026-07-12' — remove the floor and this test goes red.
    const learning = fragileLearning({ created_at: '2026-01-01T00:00:00Z' });
    const meta = toActivationMetadata(learning, { now: FROZEN_NOW });
    expect(meta.expiresAt).toBe('2026-07-12');
  });

  it('floors a FUTURE natural expiry that still falls within the 7d window', () => {
    // created_at chosen so natural expiry (created_at + 45d TTL for
    // fragile-pattern) lands at 2026-07-08 — 3 days AFTER `now` (2026-07-05),
    // i.e. `nowMs < derivedMs < nowMs + 7*DAY`. This is the genuine in-window
    // boundary case: the natural expiry is NOT already past, but it is still
    // inside the 7-day floor window, so it must be raised to now + 7 days
    // (2026-07-12) rather than passed through as 2026-07-08.
    // Fake-regression check: without the Math.max floor this would assert
    // '2026-07-08' (the un-floored natural expiry), not '2026-07-12' — remove
    // the floor and this test goes red.
    const learning = fragileLearning({ created_at: '2026-05-24T00:00:00Z' });
    const meta = toActivationMetadata(learning, { now: FROZEN_NOW });
    expect(meta.expiresAt).toBe('2026-07-12');
  });

  it('leaves a healthy future expiry unchanged (floor inert)', () => {
    // created_at 2026-06-21 + 45d = 2026-08-05, comfortably beyond now + 7d
    // (2026-07-12) for an injected `now` of 2026-07-05.
    const learning = fragileLearning({ created_at: '2026-06-21T00:00:00Z' });
    const meta = toActivationMetadata(learning, { now: FROZEN_NOW });
    expect(meta.expiresAt).toBe('2026-08-05');
  });

  it('applies the floor to an explicit ruleExpiryDays override too', () => {
    // Explicit override branch: created_at + 5 days is in the past relative
    // to `now`, so the floor must still raise it to now + 7.
    const learning = fragileLearning({ created_at: '2026-01-01T00:00:00Z' });
    const meta = toActivationMetadata(learning, {
      ruleExpiryDays: 5,
      now: FROZEN_NOW,
    });
    expect(meta.expiresAt).toBe('2026-07-12');
  });

  it('honours a custom minRuleDays floor when supplied', () => {
    const learning = fragileLearning({ created_at: '2026-01-01T00:00:00Z' });
    const meta = toActivationMetadata(learning, {
      now: FROZEN_NOW,
      minRuleDays: 14,
    });
    expect(meta.expiresAt).toBe('2026-07-19');
  });
});

describe('toActivationMetadata — never-always-on invariant', () => {
  it('throws when there is no activation axis (empty file_paths AND no host_class)', () => {
    const learning = fragileLearning({ file_paths: [] });
    expect(() => toActivationMetadata(learning, {})).toThrow(
      /never-always-on|activation axis/,
    );
  });

  it('does NOT throw when host_class is the sole axis (empty file_paths) for a HOST_SPECIFIC_TYPES type', () => {
    // #1090: host_class is only copied through for types in the
    // HOST_SPECIFIC_TYPES allow-list — 'hardware-pattern' is the only member.
    const learning = fragileLearning({
      type: 'hardware-pattern',
      file_paths: [],
      host_class: 'macos-arm64-m4pro',
    });
    const meta = toActivationMetadata(learning, {});
    expect(meta.hostClass).toBe('macos-arm64-m4pro');
  });
});

// Q3-MED fix pass: a learning record from OLD state (predating the #900 C /
// schema.mjs argv-boundary guards) can carry a glob-metacharacter file_paths
// entry (e.g. '**') — globsFromFilePaths must never emit it verbatim, since a
// top-level (dirname==='.') entry is emitted AS THE GLOB ITSELF and '**'
// would be an effectively always-on rule glob.
describe('toActivationMetadata — glob-metacharacter file_paths entries are skipped', () => {
  it('skips a "**" entry but keeps a clean sibling path as the sole glob', () => {
    const learning = fragileLearning({
      file_paths: ['**', 'scripts/lib/autopilot/worktree-pipeline.mjs'],
    });
    const meta = toActivationMetadata(learning, {});
    expect(meta.globs).toEqual(['scripts/lib/autopilot/**']);
  });

  it('throws the never-always-on invariant when "**" is the ONLY file_paths entry', () => {
    const learning = fragileLearning({ file_paths: ['**'] });
    // FALSIFICATION: emitting '**' verbatim instead of skipping it would
    // produce a non-empty globs array and this would NOT throw.
    expect(() => toActivationMetadata(learning, {})).toThrow(
      /never-always-on|activation axis/,
    );
  });

  it('skips a bracket-class glob entry (e.g. "src/[ab]/x.mjs")', () => {
    const learning = fragileLearning({
      file_paths: ['src/[ab]/x.mjs', 'scripts/lib/autopilot/worktree-pipeline.mjs'],
    });
    const meta = toActivationMetadata(learning, {});
    expect(meta.globs).toEqual(['scripts/lib/autopilot/**']);
  });

  // #1089 part B — a Next.js route-group directory (parens in a real path
  // segment) is not itself an old/malformed record; it is a LEGITIMATE path
  // that picomatch's own group syntax cannot match once turned into a glob.
  it('skips a "(marketing)" route-group path entry — either it throws, or every remaining glob would match picomatch against the path it was derived from', () => {
    const learning = fragileLearning({ file_paths: ['app/(marketing)/page.tsx'] });
    // FALSIFICATION: before #1089, this entry sailed through GLOB_METACHAR_RE
    // (which never listed `(`/`)`) and was emitted as `app/(marketing)/**` —
    // a glob picomatch.isMatch() never matches against the very path it came
    // from, proven directly below rather than asserted as a belief.
    expect(picomatch.isMatch('app/(marketing)/page.tsx', 'app/(marketing)/**')).toBe(false);

    // With the entry now skipped, the sole file_paths entry yields no glob at
    // all and no host_class → never-always-on throw (never a dead-on-arrival
    // rule). The alternative half of the contract (every SURVIVING glob does
    // match its own source path) is proven by the sibling-path test below.
    expect(() => toActivationMetadata(learning, {})).toThrow(/never-always-on|activation axis/);
  });

  it('keeps a clean sibling glob that DOES match its own source path via picomatch when a route-group entry is skipped', () => {
    const learning = fragileLearning({
      file_paths: ['app/(marketing)/page.tsx', 'scripts/lib/autopilot/worktree-pipeline.mjs'],
    });
    const meta = toActivationMetadata(learning, {});
    expect(meta.globs).toEqual(['scripts/lib/autopilot/**']);
    // The surviving glob is verified against picomatch directly — the same
    // matcher rule-loader.mjs uses at runtime — not merely shaped correctly.
    expect(
      picomatch.isMatch('scripts/lib/autopilot/worktree-pipeline.mjs', meta.globs[0]),
    ).toBe(true);
  });
});

// #1089 part A — dropped entries are recorded with a reason, not silently
// discarded behind a bare `continue`.
describe('toActivationMetadata — dropped file_paths entries are recorded (#1089)', () => {
  it('surfaces meta.droppedFilePaths with a reason for a glob-metacharacter entry', () => {
    const learning = fragileLearning({
      file_paths: ['**', 'scripts/lib/autopilot/worktree-pipeline.mjs'],
    });
    const meta = toActivationMetadata(learning, {});
    expect(meta.droppedFilePaths).toEqual([{ path: '**', reason: 'glob-metacharacter' }]);
  });

  it('surfaces meta.droppedFilePaths with a reason for a control-char/quote entry', () => {
    const learning = fragileLearning({
      file_paths: ['scripts/evil.mjs\ntier: always', 'scripts/lib/autopilot/worktree-pipeline.mjs'],
    });
    const meta = toActivationMetadata(learning, {});
    expect(meta.droppedFilePaths).toEqual([
      { path: 'scripts/evil.mjs\ntier: always', reason: 'unsafe-shape' },
    ]);
  });

  it('omits droppedFilePaths entirely when nothing was dropped', () => {
    const meta = toActivationMetadata(fragileLearning(), {});
    expect('droppedFilePaths' in meta).toBe(false);
  });
});

// ---------------------------------------------------------------------------
// #1015 — frontmatter-injection field-shape gates.
//
// These assert REJECTION, never escaping: neutralising agent text is the
// renderer's single responsibility, and escaping here as well would
// double-escape the output (a defect invisible to a file-level diff, since each
// file still reads as locally correct). Skipping/throwing is idempotent, so it
// composes with the renderer's sanitiser instead of duplicating it.
// ---------------------------------------------------------------------------

describe('toActivationMetadata — host_class shape gate (#1015)', () => {
  // `host_class` is the highest-escalation field the emitter copies: the
  // renderer serialises it as an UNQUOTED `host-class: <value>` line, so a
  // newline injects sibling TOP-LEVEL frontmatter keys. `validateLearning`
  // (learnings/schema.mjs) only asserts "string or null" — any string,
  // newlines included — so nothing upstream stops this.
  //
  // NOTE ON THE PAYLOAD: `tier: always` is used deliberately, NOT
  // `expires-at:`/`globs:`. The renderer emits `expires-at`/`globs` LATER in
  // the same frontmatter block, so an injected copy of either is overwritten
  // and the attack goes green even with no guard at all. `tier` is never
  // emitted by the renderer, so an injected `tier` SURVIVES — it is the
  // payload that actually discriminates. Do not "simplify" it back.
  it('throws when host_class carries a newline (top-level key injection)', () => {
    const learning = fragileLearning({ host_class: 'macos-arm64-m4pro\ntier: always' });
    // FALSIFICATION: without HOST_CLASS_RE this returns metadata whose
    // hostClass still carries the newline, and the renderer serialises the
    // injected `tier: always` as a real, load-bearing frontmatter key.
    expect(() => toActivationMetadata(learning, { now: FROZEN_NOW })).toThrow(/host_class/);
  });

  it('throws when host_class carries a CR (\\r line break)', () => {
    const learning = fragileLearning({ host_class: 'macos-arm64-m4pro\rtier: always' });
    expect(() => toActivationMetadata(learning, { now: FROZEN_NOW })).toThrow(/host_class/);
  });

  it('throws when host_class carries a colon (in-line key/value split)', () => {
    const learning = fragileLearning({ host_class: 'macos: always' });
    expect(() => toActivationMetadata(learning, { now: FROZEN_NOW })).toThrow(/host_class/);
  });

  it('throws when host_class carries a quote character', () => {
    const learning = fragileLearning({ host_class: 'macos"arm64' });
    expect(() => toActivationMetadata(learning, { now: FROZEN_NOW })).toThrow(/host_class/);
  });

  it('throws when host_class starts with "-" (a YAML sequence marker)', () => {
    const learning = fragileLearning({ host_class: '- injected' });
    expect(() => toActivationMetadata(learning, { now: FROZEN_NOW })).toThrow(/host_class/);
  });

  it('throws when host_class exceeds the 64-char ceiling', () => {
    const learning = fragileLearning({ host_class: 'a'.repeat(65) });
    expect(() => toActivationMetadata(learning, { now: FROZEN_NOW })).toThrow(/host_class/);
  });

  it('throws even when globs would otherwise supply the activation axis', () => {
    // The record HAS a usable file_paths glob, so the never-always-on
    // brandmauer would not fire. A malformed host_class is a corruption /
    // injection signal in its own right: refuse the whole record rather than
    // quietly emit the rest of the rule from it.
    const learning = fragileLearning({
      file_paths: ['scripts/lib/autopilot/worktree-pipeline.mjs'],
      host_class: 'macos-arm64-m4pro\ntier: always',
    });
    expect(() => toActivationMetadata(learning, { now: FROZEN_NOW })).toThrow(/host_class/);
  });

  // Over-tight-regex guard: every value classifyHost() in
  // scripts/lib/host-identity.mjs can actually produce must still pass. A gate
  // that rejects the real corpus would silently stop ALL host-scoped rule
  // proposals — a regression with no error message anywhere.
  it.each([
    'macos-arm64-m4pro',
    'macos-arm64-apple',
    'macos-x86_64',
    'linux-arm64',
    'linux-x86_64',
    'windows-arm64',
    'windows-x86_64',
    'freebsd-riscv64', // the `${osName}-${arch}` fallback branch
  ])('accepts the real classifyHost() value %s', (hostClass) => {
    // #1090: 'hardware-pattern' is the sole HOST_SPECIFIC_TYPES member — the
    // only type whose host_class is actually copied through as an axis.
    const learning = fragileLearning({ type: 'hardware-pattern', file_paths: [], host_class: hostClass });
    const meta = toActivationMetadata(learning, { now: FROZEN_NOW });
    expect(meta.hostClass).toBe(hostClass);
  });
});

// ---------------------------------------------------------------------------
// #1090 — host_class is only an activation axis for HOST_SPECIFIC_TYPES.
//
// Discovery census (2026-08-23, HEAD 01eb35d): 12/146 live learnings carry
// `host_class`, all `macos-arm64-m4pro`, all on `anti-pattern`(9) /
// `proven-pattern`(2) / `recurring-issue`(1) — NONE of them hardware-scoped
// content. Before this fix, ANY type's valid host_class was copied through
// unconditionally, so one of the corpus's own dry-run proposals would have
// shipped host-class as its SOLE activation axis on a finding that has
// nothing to do with the chip it happened to be authored on.
// ---------------------------------------------------------------------------

describe('toActivationMetadata — host_class is type-gated to HOST_SPECIFIC_TYPES (#1090)', () => {
  it('drops host_class for anti-pattern (not host-specific): meta.hostClass is undefined', () => {
    // Regression test named in the task: anti-pattern + host_class →
    // meta.hostClass undefined. file_paths stays non-empty so this returns
    // metadata instead of throwing — the point under test is the DROP, not
    // the never-always-on invariant (that is the next test).
    const learning = fragileLearning({ type: 'anti-pattern', host_class: 'macos-arm64-m4pro' });
    const meta = toActivationMetadata(learning, { now: FROZEN_NOW });
    expect(meta.hostClass).toBeUndefined();
    // Sanity: the glob axis (from file_paths) still carries the rule.
    expect(meta.globs).toEqual(['scripts/lib/autopilot/**']);
  });

  it('throws a reason naming the type-gate drop when host_class was the ONLY axis', () => {
    // FALSIFICATION: without the #1090 gate, this would return metadata with
    // hostClass set (globs is empty, so the type-gate is the only thing that
    // can make this throw at all).
    const learning = fragileLearning({
      type: 'anti-pattern',
      file_paths: [],
      host_class: 'macos-arm64-m4pro',
    });
    expect(() => toActivationMetadata(learning, { now: FROZEN_NOW })).toThrow(
      /host_class .* is present and well-formed, but type "anti-pattern" is not host-specific/,
    );
  });

  it('still throws on a malformed host_class even for a non-host-specific type (shape gate is unconditional)', () => {
    // The shape gate is a corruption/injection signal independent of whether
    // the type would ever be allowed to use the value as an axis — it must
    // fire before the type gate is even consulted.
    const learning = fragileLearning({
      type: 'anti-pattern',
      host_class: 'macos-arm64-m4pro\ntier: always',
    });
    expect(() => toActivationMetadata(learning, { now: FROZEN_NOW })).toThrow(/host_class/);
  });
});

describe('toActivationMetadata — file_paths frontmatter-structure gate (#1015)', () => {
  // The renderer emits each glob as `  - "<value>"`. A control char breaks out
  // of the block sequence into new top-level keys; a quote breaks out of the
  // quoted scalar. Both entries are SKIPPED, exactly like a glob metacharacter.
  it('skips a file_paths entry carrying a newline but keeps a clean sibling', () => {
    const learning = fragileLearning({
      file_paths: ['scripts/evil.mjs\ntier: always', 'scripts/lib/autopilot/worktree-pipeline.mjs'],
    });
    const meta = toActivationMetadata(learning, { now: FROZEN_NOW });
    expect(meta.globs).toEqual(['scripts/lib/autopilot/**']);
  });

  it('skips a file_paths entry carrying a double quote', () => {
    const learning = fragileLearning({
      file_paths: ['scripts/a".mjs', 'scripts/lib/autopilot/worktree-pipeline.mjs'],
    });
    const meta = toActivationMetadata(learning, { now: FROZEN_NOW });
    expect(meta.globs).toEqual(['scripts/lib/autopilot/**']);
  });

  it('throws the never-always-on invariant when the newline entry is the ONLY path', () => {
    // FALSIFICATION: emitting the poisoned entry verbatim would produce a
    // non-empty globs array, so this would NOT throw — and the poisoned glob
    // would reach the renderer.
    const learning = fragileLearning({ file_paths: ['scripts/evil.mjs\ntier: always'] });
    expect(() => toActivationMetadata(learning, { now: FROZEN_NOW })).toThrow(
      /never-always-on|activation axis/,
    );
  });

  it('is stateless across calls (the control-char test regex is not /g)', () => {
    // A /g regex carries lastIndex across .test() calls, so the SAME poisoned
    // input would alternate skipped/kept. Two identical calls must agree.
    const learning = fragileLearning({
      file_paths: ['scripts/evil.mjs\ntier: always', 'scripts/lib/autopilot/worktree-pipeline.mjs'],
    });
    const first = toActivationMetadata(learning, { now: FROZEN_NOW });
    const second = toActivationMetadata(learning, { now: FROZEN_NOW });
    expect(second.globs).toEqual(first.globs);
    expect(second.globs).toEqual(['scripts/lib/autopilot/**']);
  });
});

describe('toActivationMetadata — learningKey type half is VERBATIM, never slugged', () => {
  it('leaves every currently-reachable (allow-listed) type byte-identical', () => {
    // True under both the old rule (kebab is the identity for every literal in
    // eligibility.mjs's CONVERT_TYPES allow-list) and the current one — which is
    // exactly why the divergence below stayed invisible.
    const meta = toActivationMetadata(fragileLearning(), { now: FROZEN_NOW });
    expect(meta.learningKey).toBe('fragile-pattern/zx-imports');
  });

  it('does not slug the type half, so every reader derives the same key', () => {
    // This line used to kebab the type half. No READER does — not the engine's
    // rejection path, not validate/check-learning-provenance, not
    // learnings/candidates, not claude-md-drift-check. Slugging it here forks
    // the key space for the first type whose kebab is not the identity, and
    // makes the type half unrecoverable for `backfill-learnings-from-vault.mjs`,
    // which reads `learning_key.split('/')[0]` back out AS the type.
    const learning = fragileLearning({ type: 'Config_Pattern' });
    const meta = toActivationMetadata(learning, { now: FROZEN_NOW });
    expect(meta.learningKey).toBe('Config_Pattern/zx-imports');
  });

  it('leaves a newline-bearing type for the renderer to REJECT, not to silently repair', () => {
    // The kebab that used to sit here was justified as injection insurance: the
    // key becomes an unquoted `learning-key:` frontmatter line, so 'anti\ntier:
    // always' would inject a sibling `tier: always` key. That hazard is real and
    // is now closed downstream and LOUDLY — `renderer.mjs` asserts
    // LEARNING_KEY_RE (/^[a-z0-9/-]+$/) before rendering. Silently repairing it
    // here instead would re-key the record behind every reader's back.
    const learning = fragileLearning({ type: 'anti\ntier: always' });
    const meta = toActivationMetadata(learning, { now: FROZEN_NOW });
    expect(meta.learningKey).toBe('anti\ntier: always/zx-imports');
    // The safety claim, proven rather than asserted: nothing renders.
    expect(() => renderRule(learning, meta)).toThrow(/learning-key/);
  });

  it('refuses to emit a key for a learning that has no derivable identity', () => {
    const learning = fragileLearning({ subject: '!!!', title: undefined });
    expect(() => toActivationMetadata(learning, { now: FROZEN_NOW })).toThrow(
      /unkeyable learning/,
    );
  });
});

describe('toActivationMetadata — description sanitization', () => {
  it('strips newlines from the description', () => {
    const learning = fragileLearning({
      insight: 'first line\nsecond line embedded in the same sentence',
    });
    const meta = toActivationMetadata(learning, {});
    expect(meta.description.includes('\n')).toBe(false);
  });
});

describe('toActivationMetadata — learningKey source precedence', () => {
  it('prefers title over subject for the learningKey', () => {
    const learning = fragileLearning({
      title: 'Worktree Pipeline Hang',
      subject: 'zx-imports',
    });
    const meta = toActivationMetadata(learning, {});
    expect(meta.learningKey).toBe('fragile-pattern/worktree-pipeline-hang');
  });
});

describe('toActivationMetadata — confidence default', () => {
  it('defaults confidence to 0 when absent', () => {
    const learning = fragileLearning({ confidence: undefined });
    const meta = toActivationMetadata(learning, {});
    expect(meta.confidence).toBe(0);
  });
});
