/**
 * renderer.test.mjs — Unit + round-trip tests for the #695 FA2 Reconciliation
 * Engine rule renderer (`scripts/lib/reconcile/renderer.mjs`).
 *
 * The keystone here is the ROUND-TRIP: a rendered rule MUST parse back through
 * the REAL rule-loader (`scripts/lib/rule-loader.mjs`). Metadata is built with
 * the REAL emitter (`toActivationMetadata`) so renderer+emitter interop is
 * proven rather than mocked. The round-trip test writes to a per-test TEMP
 * rules dir under os.tmpdir() and cleans it up in afterEach — it never touches
 * the real `.claude/rules/`.
 */

import { describe, it, expect, afterEach } from 'vitest';
import { mkdtempSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

import { deriveSlug, renderRule } from '../../../scripts/lib/reconcile/renderer.mjs';
import { toActivationMetadata } from '../../../scripts/lib/reconcile/emitter.mjs';
import { loadApplicableRules } from '../../../scripts/lib/rule-loader.mjs';

/**
 * The canonical fragile-pattern learning used by the interop + round-trip
 * tests. file_paths under scripts/lib/autopilot → glob "scripts/lib/autopilot/**".
 * subject 'zx-imports' → learningKey 'fragile-pattern/zx-imports'.
 * created_at fixed so expires-at is deterministic.
 */
function fragileLearning(overrides = {}) {
  return {
    type: 'fragile-pattern',
    subject: 'zx-imports',
    insight: 'Top-level zx imports cause fork-pool fragility',
    confidence: 0.8,
    file_paths: ['scripts/lib/autopilot/worktree-pipeline.mjs'],
    created_at: '2026-06-21T00:00:00Z',
    id: 'L-123',
    source_session: 'deep-1',
    evidence: ['pipeline #5835 hang'],
    ...overrides,
  };
}

let tmpDirs = [];

function makeRulesDir() {
  const dir = mkdtempSync(join(tmpdir(), 'reconcile-renderer-'));
  tmpDirs.push(dir);
  return dir;
}

afterEach(() => {
  for (const dir of tmpDirs) rmSync(dir, { recursive: true, force: true });
  tmpDirs = [];
});

describe('deriveSlug', () => {
  it('is idempotent — the same learning yields an identical slug across calls', () => {
    const learning = fragileLearning();
    expect(deriveSlug(learning)).toBe(deriveSlug(learning));
  });

  it('yields a distinct slug for a learning with a distinct subject', () => {
    const a = deriveSlug(fragileLearning({ subject: 'zx-imports' }));
    const b = deriveSlug(fragileLearning({ subject: 'busy-wait-orphans' }));
    expect(a).not.toBe(b);
  });
});

describe('renderRule — frontmatter + provenance content', () => {
  it('emits loader-shaped frontmatter, block-style globs, learning-key, and a Provenance section', () => {
    const learning = fragileLearning();
    // Build metadata via the REAL emitter so renderer+emitter interop is proven.
    const metadata = toActivationMetadata(learning, { now: Date.parse('2026-06-21') });
    const { content } = renderRule(learning, metadata);

    expect(content).toContain('auto-generated: true');
    expect(content).toContain('alwaysApply: false');
    expect(content).toContain('globs:\n  - "scripts/lib/autopilot/**"');
    expect(content).toContain('learning-key: fragile-pattern/zx-imports');
    expect(content).toContain('## Provenance');
  });
});

describe('renderRule — round-trip through the real rule-loader', () => {
  it('renders a rule the loader parses as 1 glob-scoped, auto-generated entry within its expiry window', () => {
    const learning = fragileLearning();
    const metadata = toActivationMetadata(learning, { now: Date.parse('2026-06-21') });
    const { slug, content } = renderRule(learning, metadata);

    const rulesDir = makeRulesDir();
    writeFileSync(join(rulesDir, `${slug}.md`), content, 'utf8');

    const entries = loadApplicableRules({
      rulesDir,
      scopePaths: ['scripts/lib/autopilot/worktree-pipeline.mjs'],
      now: Date.parse('2026-06-21'),
    });

    expect(entries).toHaveLength(1);
    expect(entries[0].alwaysOn).toBe(false);
    expect(entries[0].autoGenerated).toBe(true);
    expect(entries[0].alwaysApply).toBe(false);
    expect(entries[0].learningKey).toBe('fragile-pattern/zx-imports');
    expect(entries[0].confidence).toBe(0.8);
  });

  it('is excluded by the loader expiry gate when now is past expires-at', () => {
    const learning = fragileLearning();
    const metadata = toActivationMetadata(learning, { now: Date.parse('2026-06-21') });
    const { slug, content } = renderRule(learning, metadata);

    const rulesDir = makeRulesDir();
    writeFileSync(join(rulesDir, `${slug}.md`), content, 'utf8');

    // expires-at is 2026-08-20; now=2026-09-01 is strictly after → excluded.
    const entries = loadApplicableRules({
      rulesDir,
      scopePaths: ['scripts/lib/autopilot/worktree-pipeline.mjs'],
      now: Date.parse('2026-09-01'),
    });

    expect(entries).toHaveLength(0);
  });
});

describe('renderRule — host-class-only round-trip through the real rule-loader', () => {
  it('omits the globs: key for a host-class-only rule so it loads on a matching host (and is excluded on a non-matching host)', () => {
    // A learning with NO file_paths but a host_class → host-class-only axis.
    const learning = fragileLearning({ file_paths: [], host_class: 'macos-arm64-m4pro' });
    const metadata = toActivationMetadata(learning, { now: Date.parse('2026-06-21') });
    // Sanity: the emitter produced empty globs + the host-class axis.
    expect(metadata.globs).toEqual([]);
    expect(metadata.hostClass).toBe('macos-arm64-m4pro');

    const { slug, content } = renderRule(learning, metadata);

    // Fix 1: no empty `globs:` line is emitted (it would short-circuit the loader).
    expect(content).not.toMatch(/^globs:/m);
    expect(content).toContain('host-class: macos-arm64-m4pro');

    const rulesDir = makeRulesDir();
    writeFileSync(join(rulesDir, `${slug}.md`), content, 'utf8');

    // On the matching host → loaded as 1 entry, gated purely by host-class.
    const matched = loadApplicableRules({
      rulesDir,
      scopePaths: ['anything/foo.ts'],
      mode: null,
      hostClass: 'macos-arm64-m4pro',
      now: Date.parse('2026-06-21'),
    });
    expect(matched).toHaveLength(1);
    expect(matched[0].hostClass).toBe('macos-arm64-m4pro');

    // On a non-matching host → excluded by the host-class gate.
    const otherHost = loadApplicableRules({
      rulesDir,
      scopePaths: ['anything/foo.ts'],
      mode: null,
      hostClass: 'some-other-host',
      now: Date.parse('2026-06-21'),
    });
    expect(otherHost).toHaveLength(0);
  });
});

describe('renderRule — never-always-on invariant', () => {
  it('throws when metadata has empty globs and no hostClass (refuses an always-on auto-generated rule)', () => {
    const learning = fragileLearning();
    const noAxisMetadata = {
      globs: [],
      description: 'no axis',
      learningKey: 'fragile-pattern/zx-imports',
      confidence: 0.8,
      expiresAt: '2026-08-20',
      autoGenerated: true,
      alwaysApply: false,
    };
    expect(() => renderRule(learning, noAxisMetadata)).toThrow(/activation axis|never-always-on/i);
  });
});
